# Generated by Django 3.0.8 on 2020-07-21 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200712_1257'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guest',
            new_name='Payers',
        ),
    ]
