# Generated by Django 3.0.8 on 2020-07-22 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_activities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='title',
        ),
    ]
